name: 'Calculate next version for a docker image (date-based)'
author: Interficie <hola@interficie.com>
description: |
  This action calculates the next date.monthday.counter version
  identifier for your docker image.
inputs:
  image:
    description: 'Image identifier, ex: repo/image'
    required: true
    default: 'wat'
outputs:
  version:
    description: 'The calculated version'
runs:
  using: 'node16'
  main: 'dist/index.js'
